language: android
sudo: true

android:
  components:
    - build-tools-23.0.1
    - android-24
    - addon-google_apis-google-24

before_install:
  - chmod +x gradlew
  - ./install-protobuf.sh

cache:
  - $HOME/.m2
  - $HOME/.gradle
  - $TRAVIS_BUILD_DIR/protobuf-2.4.1
