language: android
sudo: true

android:
  components:
    - tools
    - tools
    - build-tools-23.0.2
    - android-24
    - addon-google_apis-google-24
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew
  - ./install-protobuf.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/protobuf-2.4.1
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
