# The name of our workflow
name: Build

on:
  # Trigger on every pull request and on push
  # to the `main` branch.
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Change script permissions
        run: chmod +x ./*.sh

      - name: Set version and variables
        run: |
          VERSION=$(./gradlew printversion -q)
          echo "FIATLUX_VERSION=$VERSION" >> $GITHUB_ENV
          echo "FIATLUX_TAG=v$VERSION" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/ci:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Unpack protoc
        run: unzip ci/protoc.zip -d ci

      - name: Change script permissions
        run: chmod 775 ci/*.sh

      - name: Build the app
        run: ./ci/build.sh